# To use, run: pre-commit autoupdate then pre-commit run --all-files

exclude: chemprop-master
repos:
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile=black", "--line-length=120"]
        files: '^src/.*\.(py)$'

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: ["--line-length=120"]
        files: '^src/.*\.(py)$'

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==24.1.17
        files: '^src/.*\.(py)$'

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-isort
        additional_dependencies: ["isort==5.13.2"]
        args: ["--nbqa-mutate", "--profile=black", "--line-length=120"]
        files: '^src/.*\.ipynb$'
      - id: nbqa-black
        additional_dependencies: ["black==24.4.2"]
        args: ["--nbqa-mutate", "--line-length=120"]
        files: '^src/.*\.ipynb$'
      - id: nbqa-flake8
        additional_dependencies: ["flake8==7.0.0", "flake8-bugbear==24.1.17"]
        args: ["--max-line-length=120", "--extend-ignore=E203,W503"]
        files: '^src/.*\.ipynb$'

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        files: \.(py|ipynb)$
      - id: end-of-file-fixer
        files: \.(py|ipynb)$
      - id: check-yaml
        files: \.(py|ipynb)$
      - id: check-added-large-files
        files: \.(py|ipynb)$
